### ISSUE TITLE
Incorrect FEN

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#640]
**To reproduce the bug, follow these steps:**

1. Import the game [[game URL](https://www.chess.com/game/live/82708301999)] to a chapter.

2. Go to the 18th move (Kf8, black).

3. Copy the FEN.

4. Go to chess.com or Lichess and paste the FEN in analyze mode.

5. Move Nxc4 (19th move of White).

In chess.com and lichess, this move will be registered as the 18th move of White, even though it is the 19th move according to the original PGN file.

**#needs fixing**

How did I step into this?

When I try to import a game and then evaluate it ("Evaluate games in chapter"), the FEN for white moves is incorrect. This causes Stockfish and Leela Chess Zero to crash.

I have attached the [game](https://www.chess.com/game/live/5134397257?username=selvasumi) of the crash message from Leela Chess Zero and Stockfish.

https://docs.google.com/spreadsheets/d/1wjPtRvrbqxqPleoS5JuPO2hkmfBtcYDDWprkC7O-VNw/edit?usp=sharing
![Screenshot (339)](https://github.com/czbar/ChessForge/assets/125844120/fae8d714-a357-499f-bca6-0ea8a0294d38)

I believe this is caused by an incorrect FEN for white moves being supplied by ChessForge.
Would you be able to take a look at this issue and see if you can find a solution?

**Comment by czbar** [comment]
Sure, I'll certainly have a look and resolve the issue (as well as the other issues you have raised recently). It may have to wait a few more days as I am in the middle of a trip across Central America right now. From next Tuesday I'll be staying put in Costa Rica for another 2 months so I'll start clearing the backlog while there!

**Comment by akaKarthick** [comment]
Enjoy your wonderful trip. 💐😉

**Comment by czbar** [comment]
Just fixed it (in private build 1.2.1 that I will publish in a few days).  Indeed, Chess Forge was generated move numbers half-move too early.

Just to be sure that I fixed everything, can you please elaborate on "_When I try to import a game and then evaluate it ("Evaluate games in chapter"), the FEN for white moves is incorrect. This causes Stockfish and Leela Chess Zero to crash._" In what environment were the engines crashing?  In Chess Forge or elsewhere?

**Comment by akaKarthick** [comment]
I guess you fixed it.

**Comment by akaKarthick** [comment]
> Just to be sure that I fixed everything, can you please elaborate on "When I try to import a game and then evaluate it ("Evaluate games in chapter"), the FEN for white moves is incorrect. This causes Stockfish and Leela Chess Zero to crash." In what environment were the engines crashing? In Chess Forge or elsewhere?

https://youtu.be/1f6x1-VGEWQ

This is what i saw on that day. Leela not accepting the move 14.Bxa8.and crashed.

Stockfish understand the move and still continued. But after 23 rd move its crashed. dont know why. Maybe bad FEN in pgn.

But how is it possible? That game was played in online. 

https://www.chess.com/game/live/5134397257?username=selvasumi

[Event "Live Chess"]
[Site "Chess.com"]
[Date "2020.07.11"]
[Round "?"]
[White "selvasumi"]
[Black "Akshat102"]
[Result "1-0"]
[ECO "D02"]
[WhiteElo "396"]
[BlackElo "478"]
[TimeControl "300"]
[EndTime "9:23:20 PDT"]
[Termination "selvasumi won on time"]

1. d4 d5 2. Nf3 Bg4 3. h3 Bf5 4. g4 Be4 5. Bg2 Bxf3 6. Bxf3 Qd6 7. e4 dxe4 8.
Bxe4 Qe6 9. f3 f5 10. gxf5 Qd6 11. Bxb7 Qg3+ 12. Ke2 Qg2+ 13. Kd3 g6 14. Bxa8
Na6 15. fxg6 hxg6 16. f4 Qxa8 17. Nc3 e5 18. fxe5 Bb4 19. a3 Bxc3 20. bxc3 Nh6
21. Rf1 Nf5 22. Bg5 Ng3 23. Rf3 Rxh3 24. Rxg3 Rxg3+ 25. Ke2 Qf3+ 26. Ke1 Rg1+
27. Kd2 Rxd1+ 28. Rxd1 Qg2+ 29. Kd3 1-0


Is this new issue? or same issue?

**Comment by akaKarthick** [comment]
this game also 
https://www.chess.com/game/live/68647953759

**Comment by czbar** [comment]
Indeed, the rook capture is causing the problem!  There is a bug in the way FEN is generated (and passed on to the engine) whereby the castling rights are not updated (removed) when the rook is captured. The FEN incorrectly indicates that Black still has the right to castle to the side where the rook was actually captured.  Stockfish behaves totally unpredictably when facing an error (the developers have refused for years to handle/report errors) and sends garbage moves back (e.g., long castle for Black on the first rank :)) which Chess Forge does not handle gracefully (I will fix that too, btw). I don't know much about Leela yet, but it seems to handle errors differently.  I'll look into that later. The end result is the same, though.   

Great find!

**Comment by czbar** [comment]
Just for the record: this part of my above comment is not accurate "_whereby the castling rights are not updated (removed) when the rook is captured_."  In fact, the code has always been checking for that. The bug was that in some circumstances (when white has no castling right), the check was skipped! It's fixed now.
